Developing
iho-ohi/S-102-Product-Specification pull request #24
Opened 2023-02-09 19:55 UTC by hasel001

Includes Raphael edits (via Word) circa 24 January 2023 and Svein previously adopted changes resubmitted to Lawrence around PT11. Annexes for feature catalogue and gridding method were removed.

2023-02-10 07:55 UTC, rmalyankar commented
> Includes Raphael edits (via Word) circa 24 January 2023 and Svein previously adopted changes resubmitted to Lawrence around PT11. Annexes for feature catalogue and gridding method were removed.

There are a few discrepancies between my edits and the 9 February Github adoc version in clause 12, for example a note I deleted in the S100_ProtectionScheme table is apparently still there.

2023-02-10 20:16 UTC, hasel001 commented
@rmalyankar Thanks for catching that missed deletion. I fixed it along with a couple of "Note" elements that had been appearing in one cell at the bottom of the nearest table instead of below the entire table. 

The PDF generated in the github_pages.zip artifact is quite broken--it is over 500 pages due to many table cells insisting upon occupying one line by themselves.

The Word doc is far from perfect, but it is beginning to resemble our Spec.

2023-04-05 12:48 UTC, RohdeBSH requested changes
Answer to issue #35 

There are many inconsistencies and questions in the amendments. Problems exist both structurally and in terms of content. Therefore, I can not agree with the MergeRequest.

--
In many tables, the header is not highlighted in gray. So the header is not correctly marked as "header".

--
Why is the Portrayal Catalogue an Appendix and not an Annex?

2023-04-05 13:11 UTC, hasel001 commented on sources/2.2.0/sections/01-overview.adoc
I had failed to change the S-100 version in [Product Specification metadata], so I changed it just now (as well as changing the date to April 2023 for ours). If the Ed. 4.0.0 persists, it may need to be programatically handled in the MN machinery. I will ensure the edition number is corrected (manually if necessary) in the published version.

2023-04-05 13:29 UTC, hasel001 commented on sources/2.2.0/sections/10-data_product_format.adoc
>  [cols="<a,<a,<a,^a,<a,<a"]
Done

2023-04-05 13:29 UTC, hasel001 commented on sources/2.2.0/sections/10-data_product_format.adoc
> +image::../images/figure-hierarchy-of-s102-data-product-nozero.png[]
Agreed and changed

2023-04-05 13:29 UTC, hasel001 commented on sources/2.2.0/sections/10-data_product_format.adoc
> +|QualityOfSurvey +
I am adding it to be consistent with BathymetryCoverage

2023-04-05 13:37 UTC, hasel001 commented on sources/2.2.0/sections/10-data_product_format.adoc
> +^|
Is the proper value here 0..1 or 1?

2023-04-05 13:40 UTC, hasel001 commented on sources/2.2.0/sections/10-data_product_format.adoc
> +//real name needed (RM comment 4Jan2023)
I removed "id"

2023-04-05 13:42 UTC, hasel001 commented on sources/2.2.0/sections/10-data_product_format.adoc
> +==== Mandatory Naming Conventions
Removed

2023-04-05 13:43 UTC, hasel001 commented on sources/2.2.0/sections/10-data_product_format.adoc
> +The following group and attribute names are mandatory in S-100: Group_F, featureCode, and (for S-102) *BathymetryCoverage*, axisNames, *BathymetryCoverage01*, and Group_nnn.
Duplicate material removed

2023-04-05 13:59 UTC, RohdeBSH commented on sources/2.2.0/sections/10-data_product_format.adoc
> +^|
Since the BSH does not have this information, I tend to 0..1.

The topic was discussed in #16

2023-04-06 03:20 UTC, ronaldtse commented on sources/2.2.0/sections/01-overview.adoc
I’m on a trip right now but will check once I get back to a computer tonight. The thing is I’m not sure if we have S-100 5.0.0 encoded in the bibliographic database. Ping @andrew2net.

2023-04-06 04:29 UTC, andrew2net commented on sources/2.2.0/sections/01-overview.adoc
relaton-data-iho has only [IHO S-100 4.0.0](https://github.com/relaton/relaton-data-iho/blob/master/data/s-100_4-0-0.yaml)

2023-04-08 07:36 UTC, ronaldtse commented on sources/2.2.0/sections/01-overview.adoc
The issue to encode the IHO S-100 5.0.0 bibliographic item is here:
* https://github.com/relaton/relaton-data-iho/issues/18

The issue about the invalid link is here:
* https://github.com/metanorma/metanorma-iho/issues/138

2023-04-11 01:25 UTC, ronaldtse commented on sources/2.2.0/sections/01-overview.adoc
@hasel001 the reference to S-100 5.0.0 will work once this is resolved:
* https://github.com/metanorma/metanorma-iho/issues/143

You will have to change:
```adoc
[bibliography]
=== References
* [[[iho-s100,IHO S-100]]]
```

To:
```adoc
[bibliography]
=== References
* [[[iho-s100,IHO S-100 5.0.0]]]
```

2023-04-11 14:00 UTC, ronaldtse commented
@hasel001 I'd like to mention that there is one validation error in the document:

```
Anchors: (XML Line 001340): Crossreference target tab-codes-defining-how-uncertainty-was-determined is undefined
```

It looks like a table is missing in the document?

2023-04-24 13:47 UTC, hasel001 commented
@rmalyankar , thank you very much for the changes summary you sent me. I have incorporated it into the Document History section. As we continue considering rolling all these changes into the main branch, please review and comment on the updated Document History. Thank you!

2023-04-28 09:57 UTC, RohdeBSH reviewed
Good work so far.

2023-04-28 09:57 UTC, RohdeBSH commented on sources/2.2.0/sections/10-data_product_format.adoc
> -_Attribute_:: a named data value associated with a group, dataset, or named datatype and stored as a scalar;
Does anyone have a problem with restoring this text?
If not, I will do it on 03 May 2023.

2023-05-08 04:24 UTC, RohdeBSH approved these changes
Now everything is Okay

2023-05-08 18:33 UTC, merged