Draft validation checks annex for Ed. 2.3.0
iho-ohi/S-102-Product-Specification pull request #58
Opened 2023-08-22 04:33 UTC by rmalyankar

Includes draft annex, spreadsheet of "product-specific" validation checks,  and correction to minor typo in clause 10.

2023-09-05 10:37 UTC, RohdeBSH requested changes
I wrote some comments to the file "sources/2.3.0/sections/aj-validation-checks.adoc" which should be answered before the merge.

2023-09-05 10:55 UTC, rmalyankar commented on sources/2.3.0/sections/aj-validation-checks.adoc
> +Generalised checks for Exchange Set validation are being developed by the S-100WG and will be introduced into S-104 when ready.
Updated to S-102

2023-09-05 10:55 UTC, rmalyankar commented on sources/2.3.0/sections/aj-validation-checks.adoc
> +| 2	| Validate Feature Container Groups	| Validation of metadata and structure for each feature type (“Feature Container”). In S-104 there is only one feature container, so this set of checks is exec
Updated to S-102

2023-09-05 10:58 UTC, rmalyankar commented on sources/2.3.0/sections/aj-validation-checks.adoc
> +.Classification of checks
Where in S-100 is this documented? There is no overarching document for validation checks for all product specifications in S-100.

2023-09-05 11:02 UTC, rmalyankar commented
Made changes and replied to comments. Do the changes appear in your view of the pull request?

2023-09-05 11:20 UTC, RohdeBSH commented on sources/2.3.0/sections/aj-validation-checks.adoc
> +.Classification of checks
Then it's okay.
I just thought that this topic is described somewhere in the S-100 documents centrally for all product specifications.

2023-09-05 11:22 UTC, RohdeBSH approved these changes
It's okay.

2023-09-07 16:25 UTC, hasel001 approved these changes

2023-09-07 16:25 UTC, merged